name: Firmware Submission (Single Target)
description: Submit firmware update(s) for devices with a single upgradable target on target 0
labels: ['pending-approval']
body:
  - type: markdown
    attributes:
      value: |
        Use this form to submit firmware updates for Z-Wave devices that only have a single upgradable chip/target.
        This form assumes the update is for chip/target `0`. To provide updates for a different chip/target, use the `Firmware Submission` form instead or open a PR directly.

        Multiple device entries can be used to match multiple devices/models.

        Multiple upgrades can be used to submit multiple firmwares for the same device at once,
        either different versions or different region-specific updates.

        For details, see the [documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md).

  - type: markdown
    attributes:
      value: '## Device 1'

  - type: input
    id: brand
    attributes:
      label: Brand
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      placeholder: e.g. ZWA-002
    validations:
      required: true

  - type: input
    id: manufacturer-id
    attributes:
      label: Manufacturer ID
      description: 4-digit hex, e.g. 0xd3ad
    validations:
      required: true

  - type: input
    id: product-type
    attributes:
      label: Product Type
      description: 4-digit hex, e.g. 0xb33f
    validations:
      required: true

  - type: input
    id: product-id
    attributes:
      label: Product ID
      description: 4-digit hex, e.g. 0xc4f3
    validations:
      required: true

  - type: input
    id: firmware-version-min
    attributes:
      label: Firmware Version (Min)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '0.0'
    validations:
      required: false

  - type: input
    id: firmware-version-max
    attributes:
      label: Firmware Version (Max)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '255.255'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Device 2 (optional)'

  - type: input
    id: brand-2
    attributes:
      label: Brand (Device 2)
    validations:
      required: false

  - type: input
    id: model-2
    attributes:
      label: Model (Device 2)
      placeholder: e.g. ZWA-002
    validations:
      required: false

  - type: input
    id: manufacturer-id-2
    attributes:
      label: Manufacturer ID (Device 2)
      description: 4-digit hex, e.g. 0xd3ad
    validations:
      required: false

  - type: input
    id: product-type-2
    attributes:
      label: Product Type (Device 2)
      description: 4-digit hex, e.g. 0xb33f
    validations:
      required: false

  - type: input
    id: product-id-2
    attributes:
      label: Product ID (Device 2)
      description: 4-digit hex, e.g. 0xc4f3
    validations:
      required: false

  - type: input
    id: firmware-version-min-2
    attributes:
      label: Firmware Version (Min) (Device 2)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '0.0'
    validations:
      required: false

  - type: input
    id: firmware-version-max-2
    attributes:
      label: Firmware Version (Max) (Device 2)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '255.255'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Device 3 (optional)'

  - type: input
    id: brand-3
    attributes:
      label: Brand (Device 3)
    validations:
      required: false

  - type: input
    id: model-3
    attributes:
      label: Model (Device 3)
      placeholder: e.g. ZWA-002
    validations:
      required: false

  - type: input
    id: manufacturer-id-3
    attributes:
      label: Manufacturer ID (Device 3)
      description: 4-digit hex, e.g. 0xd3ad
    validations:
      required: false

  - type: input
    id: product-type-3
    attributes:
      label: Product Type (Device 3)
      description: 4-digit hex, e.g. 0xb33f
    validations:
      required: false

  - type: input
    id: product-id-3
    attributes:
      label: Product ID (Device 3)
      description: 4-digit hex, e.g. 0xc4f3
    validations:
      required: false

  - type: input
    id: firmware-version-min-3
    attributes:
      label: Firmware Version (Min) (Device 3)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '0.0'
    validations:
      required: false

  - type: input
    id: firmware-version-max-3
    attributes:
      label: Firmware Version (Max) (Device 3)
      description: Only needed when the same model has multiple definition files split by version range, for example 1.0-2.255 and 3.0+
      placeholder: '255.255'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Upgrade 1'

  - type: input
    id: version
    attributes:
      label: Firmware Version
      description: Version of the new firmware, e.g. 1.23
      placeholder: '1.23'
    validations:
      required: true

  - type: textarea
    id: changelog
    attributes:
      label: Changelog
      description: This will be shown to users to explain what's new in this firmware update, so be sure to include any important details or bug fixes. Markdown formatting is supported.
      placeholder: "* Fixed some bugs\n* Added new features\n* Introduced other bugs"
    validations:
      required: true

  - type: dropdown
    id: channel
    attributes:
      label: Channel
      description: Can be used to provide a beta firmware to a subset of users for testing before rolling out to everyone.
      options:
        - stable
        - beta
    validations:
      required: true

  - type: dropdown
    id: region
    attributes:
      label: Region
      description: Select a region if this update is region-specific, otherwise leave as "All regions"
      options:
        - All regions
        - europe
        - usa
        - 'australia/new zealand'
        - hong kong
        - india
        - israel
        - russia
        - china
        - japan
        - korea
    validations:
      required: true

  - type: input
    id: if-condition
    attributes:
      label: Upgrade conditions
      description: |
        Can be used to limit upgrade paths to this firmware, e.g. `firmwareVersion >= 1.5 && firmwareVersion < 2.0`  
        [Documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#offer-upgrades-conditionally)
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Firmware URL
      placeholder: 'https://example.com/firmware/v1.23.ota'
    validations:
      required: true

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Upgrade 2 (optional)'

  - type: input
    id: version-2
    attributes:
      label: Firmware Version (Upgrade 2)
      description: Version of the new firmware, e.g. 1.23
      placeholder: '1.23'
    validations:
      required: false

  - type: textarea
    id: changelog-2
    attributes:
      label: Changelog (Upgrade 2)
      description: This will be shown to users to explain what's new in this firmware update, so be sure to include any important details or bug fixes. Markdown formatting is supported.
      placeholder: "* Fixed some bugs\n* Added new features\n* Introduced other bugs"
    validations:
      required: false

  - type: dropdown
    id: channel-2
    attributes:
      label: Channel (Upgrade 2)
      description: Can be used to provide a beta firmware to a subset of users for testing before rolling out to everyone.
      options:
        - stable
        - beta
    validations:
      required: false

  - type: dropdown
    id: region-2
    attributes:
      label: Region (Upgrade 2)
      description: Select a region if this update is region-specific, otherwise leave as "All regions"
      options:
        - All regions
        - europe
        - usa
        - 'australia/new zealand'
        - hong kong
        - india
        - israel
        - russia
        - china
        - japan
        - korea
    validations:
      required: false

  - type: input
    id: if-condition-2
    attributes:
      label: Upgrade conditions (Upgrade 2)
      description: |
        Can be used to limit upgrade paths to this firmware, e.g. `firmwareVersion >= 1.5 && firmwareVersion < 2.0`  
        [Documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#offer-upgrades-conditionally)
    validations:
      required: false

  - type: input
    id: url-2
    attributes:
      label: Firmware URL (Upgrade 2)
      placeholder: 'https://example.com/firmware/v1.23.ota'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Upgrade 3 (optional)'

  - type: input
    id: version-3
    attributes:
      label: Firmware Version (Upgrade 3)
      description: Version of the new firmware, e.g. 1.23
      placeholder: '1.23'
    validations:
      required: false

  - type: textarea
    id: changelog-3
    attributes:
      label: Changelog (Upgrade 3)
      description: This will be shown to users to explain what's new in this firmware update, so be sure to include any important details or bug fixes. Markdown formatting is supported.
      placeholder: "* Fixed some bugs\n* Added new features\n* Introduced other bugs"
    validations:
      required: false

  - type: dropdown
    id: channel-3
    attributes:
      label: Channel (Upgrade 3)
      description: Can be used to provide a beta firmware to a subset of users for testing before rolling out to everyone.
      options:
        - stable
        - beta
    validations:
      required: false

  - type: dropdown
    id: region-3
    attributes:
      label: Region (Upgrade 3)
      description: Select a region if this update is region-specific, otherwise leave as "All regions"
      options:
        - All regions
        - europe
        - usa
        - 'australia/new zealand'
        - hong kong
        - india
        - israel
        - russia
        - china
        - japan
        - korea
    validations:
      required: false

  - type: input
    id: if-condition-3
    attributes:
      label: Upgrade conditions (Upgrade 3)
      description: |
        Can be used to limit upgrade paths to this firmware, e.g. `firmwareVersion >= 1.5 && firmwareVersion < 2.0`  
        [Documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#offer-upgrades-conditionally)
    validations:
      required: false

  - type: input
    id: url-3
    attributes:
      label: Firmware URL (Upgrade 3)
      placeholder: 'https://example.com/firmware/v1.23.ota'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '---'

  - type: markdown
    attributes:
      value: '## Upgrade 4 (optional)'

  - type: input
    id: version-4
    attributes:
      label: Firmware Version (Upgrade 4)
      description: Version of the new firmware, e.g. 1.23
      placeholder: '1.23'
    validations:
      required: false

  - type: textarea
    id: changelog-4
    attributes:
      label: Changelog (Upgrade 4)
      description: This will be shown to users to explain what's new in this firmware update, so be sure to include any important details or bug fixes. Markdown formatting is supported.
      placeholder: "* Fixed some bugs\n* Added new features\n* Introduced other bugs"
    validations:
      required: false

  - type: dropdown
    id: channel-4
    attributes:
      label: Channel (Upgrade 4)
      description: Can be used to provide a beta firmware to a subset of users for testing before rolling out to everyone.
      options:
        - stable
        - beta
    validations:
      required: false

  - type: dropdown
    id: region-4
    attributes:
      label: Region (Upgrade 4)
      description: Select a region if this update is region-specific, otherwise leave as "All regions"
      options:
        - All regions
        - europe
        - usa
        - 'australia/new zealand'
        - hong kong
        - india
        - israel
        - russia
        - china
        - japan
        - korea
    validations:
      required: false

  - type: input
    id: if-condition-4
    attributes:
      label: Upgrade conditions (Upgrade 4)
      description: |
        Can be used to limit upgrade paths to this firmware, e.g. `firmwareVersion >= 1.5 && firmwareVersion < 2.0`  
        [Documentation](https://github.com/zwave-js/firmware-updates/blob/main/docs/firmware-files.md#offer-upgrades-conditionally)
    validations:
      required: false

  - type: input
    id: url-4
    attributes:
      label: Firmware URL (Upgrade 4)
      placeholder: 'https://example.com/firmware/v1.23.ota'
    validations:
      required: false
