name: 'Z-Wave Bot: Label official PRs'

on:
  pull_request:
    types: [synchronize, reopened]
  pull_request_review:
    types: [submitted, edited]

jobs:
  # #########################################################################
  # Labels PRs opened by a known manufacturer account
  label-official:
    # Don't run in forks, don't run for drafts
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.draft == false

    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            const action = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/bot_label-official-prs.js`);
            action({github, context});


  # #########################################################################
  # Labels PRs reviewed by a known manufacturer account
  label-official-reviews:
    # Don't run in forks, don't run for drafts
    if: |
      github.event_name == 'pull_request_review' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.draft == false

    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            const action = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/bot_label-official-reviews.js`);
            action({github, context});
